Models/ApiHelper.cs
using System.Threading.Tasks;
using RestSharp;

namespace TravelAPIClient.Models
{
    class ApiHelper
    {
        public static async Task<string> GetAll()
        {
            RestClient client = new RestClient("http://localhost:5004/api");
            RestRequest request = new RestRequest($"destinations", Method.GET);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task<string> Get(int id)
        {
            RestClient client = new RestClient("http://localhost:5004/api");
            RestRequest request = new RestRequest($"destinations/{id}", Method.GET);
            var response = await client.ExecuteTaskAsync(request);
            return response.Content;
        }

        public static async Task Post(string newDestination)
        {
            RestClient client = new RestClient("http://localhost:5004/api");
            RestRequest request = new RestRequest($"destinations", Method.POST);
            request.AddHeader("Content-Type", "application/json");
            request.AddJsonBody(newDestination);
            var response = await client.ExecuteTaskAsync(request);
        }

        public static async Task Put(int id, string newDestination)
        {
            RestClient client = new RestClient("http://localhost:5004/api");
            RestRequest request = new RestRequest($"destinations/{id}", Method.PUT);
            request.AddHeader("Content-Type", "application/json");
            request.AddJsonBody(newDestination);
            var response = await client.ExecuteTaskAsync(request);
        }

        public static async Task Delete(int id)
        {
            RestClient client = new RestClient("http://localhost:5004/api");
            RestRequest request = new RestRequest($"destinations/{id}", Method.DELETE);
            request.AddHeader("Content-Type", "application/json");
            var response = await client.ExecuteTaskAsync(request);
        }
    }
}

Models/Destination.cs
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace TravelAPIClient.Models
{
    public class Destination
    {
        public Destination()
        {
            this.Reviews = new HashSet<Review>();
        }

        public int DestinationID {get; set; }
        [Required]
        [StringLength(20)]
        public string Name {get; set; }
        [Required]
        [StringLength(20)]
        public string City {get; set; }
        [Required]
        [StringLength(20)]
        public string Country {get; set; }

        public virtual ICollection<Review> Reviews {get; set; }

        public static List<Destination> GetDestinations()
        {
            var apiCallTask = ApiHelper.GetAll();
            var result = apiCallTask.Result;

            JArray jsonResponse = JsonConvert.DeserializeObject<JArray>(result);
            List<Destination> destinationList = JsonConvert.DeserializeObject<List<Destination>>(jsonResponse.ToString());

            return destinationList;
        }

        public static Destination GetDetails(int id)
        {
            var apiCallTask = ApiHelper.Get(id);
            var result = apiCallTask.Result;

            JObject jsonResponse = JsonConvert.DeserializeObject<JObject>(result);
            Destination destination = JsonConvert.DeserializeObject<Destination>(jsonResponse.ToString());

            return destination;
        }

       public static void Post(Destination destination)
        {
            string jsonDestination = JsonConvert.SerializeObject(destination);
            var apiCallTask = ApiHelper.Post(jsonDestination);
        }

        public static void Put(Destination destination)
        {
            string jsonDestination = JsonConvert.SerializeObject(destination);
            var apiCallTask = ApiHelper.Put(destination.DestinationID, jsonDestination);
        }

        public static void Delete(int id)
        {
            var apiCallTask = ApiHelper.Delete(id);
        }


    }
}

Models/ErrorViewModel.cs
using System;

namespace TravelAPIClient.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Review.cs
using System.ComponentModel.DataAnnotations;

namespace TravelAPIClient.Models
{
    public class Review
    {
        public int ReviewID {get; set; }
        [Required]
        public int DestinationID {get; set; }
        [Required]
        [Range(0,5)]
        public int Rating {get; set; }
        [Required]
        public string Description {get; set; }
    }
    
}

Models/TravelAPIClientContext.cs
using Microsoft.EntityFrameworkCore;

namespace TravelAPIClient.Models
{
    public class TravelAPIClientContext : DbContext
    {
        public DbSet<Destination> Destinations {get; set; }
        public DbSet<Review> Reviews {get; set; }

        public TravelAPIClientContext(DbContextOptions<TravelAPIClientContext> options) : base(options) 
        {

        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseLazyLoadingProxies();
        }


    }

}

Controllers/DestinationsController.cs
using Microsoft.AspNetCore.Mvc;
using TravelAPIClient.Models;

namespace TravelAPIClient.Controllers
{
    public class DestinationsController : Controller
    {
        public IActionResult Index()
        {
            var allDestinations = Destination.GetDestinations();
            return View(allDestinations);
        }

        public IActionResult Details(int id)
        {
            var thisDestination = Destination.GetDetails(id);
            return View(thisDestination);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Destination destination)
        {
            Destination.Post(destination);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            var thisDestination = Destination.GetDetails(id);
            return View(thisDestination);
        }

        [HttpPost]
        public IActionResult Edit(Destination destination)
        {
            Destination.Put(destination);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var thisDestination = Destination.GetDetails(id);
            return View(thisDestination);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeleteConfirmed(int id)
        {
            Destination.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TravelAPIClient.Models;

namespace TravelAPIClient.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Destinations/Create.cshtml
@model TravelAPIClient.Models.Destination
<h1>Create Destination:</h1>
@using (Html.BeginForm())
{
  <div class="mb-3">
    @Html.LabelFor(model => model.Name, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required="required"})
  </div>
  <div class="mb-3">
    @Html.LabelFor(model => model.City, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.City, new { @class = "form-control", required="required"})
  </div>
  <div class="mb-3">
    @Html.LabelFor(model => model.Country, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.Country, new { @class = "form-control", required="required"})
  </div>

  <input type="submit" value="Add Destination" class="btn btn-dark btn-block" />
}

Views/Destinations/Delete.cshtml
@model TravelAPIClient.Models.Destination
<h1>Delete Destination:</h1>
<ol>
    <ul>
        <li>ID: @Model.DestinationID</li>
        <li>Name: @Model.Name</li>
        <li>City: @Model.City</li>
        <li>Country: @Model.Country</li>
    </ul>
</ol>
@using (Html.BeginForm())
{
  <input type="submit" value="Delete Destination" class="btn btn-danger" />
}

Views/Destinations/Details.cshtml
@model TravelAPIClient.Models.Destination
<h1>Destination Details:</h1>
@Html.ActionLink("Edit this destination", "Edit", new { id = @Model.DestinationID})
<br> 
@Html.ActionLink("Delete destination", "Delete", new { id = @Model.DestinationID})
<ol>
    <ul>
        <li>ID: @Model.DestinationID</li>
        <li>Name: @Model.Name</li>
        <li>City: @Model.City</li>
        <li>Country: @Model.Country</li>
    </ul>
</ol>

Views/Destinations/Edit.cshtml
@model TravelAPIClient.Models.Destination
<h1>Edit Destination:</h1>
@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.DestinationID)
  <div class="mb-3">
    @Html.LabelFor(model => model.Name, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.Name, new { @class = "form-control", required="required"})
  </div>
  <div class="mb-3">
    @Html.LabelFor(model => model.City, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.City, new { @class = "form-control", required="required"})
  </div>
  <div class="mb-3">
    @Html.LabelFor(model => model.Country, new { @class = "form-label"})
    @Html.TextBoxFor(model => model.Country, new { @class = "form-control", required="required"})
  </div>

  <input type="submit" value="Save Destination" class="btn btn-dark btn-block" />
}

Views/Destinations/Index.cshtml
<h1>All Destinations:</h1>
@Html.ActionLink("Add new destination", "Create", "Destinations")
<ol>
@foreach (Destination destination in Model)
{
    <p><strong>@destination.Name</strong></p>
    <ul>
        <li>ID: @destination.DestinationID</li>
        <li>City: @destination.City</li>
        @if (@destination.Country == null)
        {
        <li>Country: N/A</li>
        }
        else
        {
        <li>Country: @destination.Country</li>
        }
    </ul>
    <a href="/Destinations/Details/@(destination.DestinationID)"><p>View Details</p></a>
    <br>
}
</ol>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TravelAPIClient</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">TravelAPIClient</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" href='@Url.Action("Index", "Destinations")'>Destinations</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - TravelAPIClient - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>